services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  web:
    build:
      context: ./backend/Cook/ICookThis
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=RecipesDb;User Id=sa;Password=Password1!;TrustServerCertificate=True
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./frontend/ICookThisFront
      dockerfile: Dockerfile
    depends_on:
      - web
    environment:
      # jeżeli w Vite używamy zmiennej VITE_API_BASE_URL
      - VITE_API_BASE_URL=http://web/api
    ports:
      - "8080:80"
    networks:
      - default

  # do usunięcia w przyszłości
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend/ICookThisFront:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - web

volumes:
  sqlserver_data:

networks:
  default: